# Generated by Django 4.2.6 on 2023-11-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topico',
        ),
    ]
