# Generated by Django 4.2.6 on 2023-11-16 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0003_delete_topico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Topico',
        ),
    ]
