# Generated by Django 4.2.6 on 2023-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_rename_evento_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('canceled', 'canceled')], default='ongoing', max_length=50),
        ),
    ]
