# Generated by Django 4.2.6 on 2023-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_topico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='updatedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
